07/27/2024 02:44:45 PM Logging starts
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/beatriz/L3/src/l3/CoverageManager.py", line 38, in save
    self._save_metrics(file, predictor_name)
  File "/home/beatriz/L3/src/l3/CoverageManager.py", line 31, in _save_metrics
    'coverage_percentage': [len(self.executed_lines)/total_lines]
ZeroDivisionError: division by zero
1.55user 4.07system 0:00.74elapsed 755%CPU (0avgtext+0avgdata 68600maxresident)k
0inputs+8outputs (0major+20027minor)pagefaults 0swaps
