07/27/2024 07:46:52 PM Logging starts
Traceback (most recent call last):
  File "./popular_projects_snippets_dataset/black/bodies/body_293_guide_9_1.py", line 35, in <module>
    raise LookupError("Opening paren not found in `leaves`")
LookupError: Opening paren not found in `leaves`
Command exited with non-zero status 1
1.47user 4.13system 0:00.80elapsed 698%CPU (0avgtext+0avgdata 108464maxresident)k
0inputs+40outputs (0major+25221minor)pagefaults 0swaps
