07/28/2024 09:10:22 AM Logging starts
Traceback (most recent call last):
  File "./popular_projects_snippets_dataset/flask/bodies/body_111_refine_3_6.py", line 126, in <module>
    cli.load_dotenv()
TypeError: <lambda>() takes 0 positional arguments but 1 was given
Command exited with non-zero status 1
1.71user 4.74system 0:00.73elapsed 880%CPU (0avgtext+0avgdata 118008maxresident)k
0inputs+24outputs (0major+21622minor)pagefaults 0swaps
