07/27/2024 10:02:11 PM Logging starts
Traceback (most recent call last):
  File "./popular_projects_snippets_dataset/flask/bodies/body_143_guide_1_3.py", line 164, in <module>
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "./popular_projects_snippets_dataset/flask/bodies/body_143_guide_1_3.py", line 9, in build
    raise BuildError() # pragma: no cover
TypeError: __init__() missing 3 required positional arguments: 'endpoint', 'values', and 'method'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 2126, in shutdown
    h.flush()
  File "/usr/lib/python3.8/logging/__init__.py", line 1068, in flush
    if self.stream and hasattr(self.stream, "flush"):
  File "/home/beatriz/L3/l3_env/lib/python3.8/site-packages/werkzeug/local.py", line 318, in __get__
    obj = instance._get_current_object()
  File "/home/beatriz/L3/l3_env/lib/python3.8/site-packages/werkzeug/local.py", line 526, in _get_current_object
    return get_name(local())
  File "/home/beatriz/L3/l3_env/lib/python3.8/site-packages/flask/logging.py", line 25, in wsgi_errors_stream
    if request:
  File "/home/beatriz/L3/l3_env/lib/python3.8/site-packages/werkzeug/local.py", line 318, in __get__
    obj = instance._get_current_object()
  File "/home/beatriz/L3/l3_env/lib/python3.8/site-packages/werkzeug/local.py", line 521, in _get_current_object
    return get_name(obj)
AttributeError: 'NoneType' object has no attribute 'request'
Command exited with non-zero status 1
1.73user 4.31system 0:00.91elapsed 663%CPU (0avgtext+0avgdata 117004maxresident)k
0inputs+80outputs (0major+20569minor)pagefaults 0swaps
