07/27/2024 06:44:16 PM Logging starts
Traceback (most recent call last):
  File "./popular_projects_snippets_dataset/flask/bodies/body_353_refine_3_2.py", line 79, in <module>
    response = super().open(
RuntimeError: super(): no arguments
Command exited with non-zero status 1
1.50user 4.17system 0:00.76elapsed 741%CPU (0avgtext+0avgdata 112044maxresident)k
0inputs+64outputs (0major+25242minor)pagefaults 0swaps
