07/28/2024 10:38:39 AM Logging starts
Traceback (most recent call last):
  File "./popular_projects_snippets_dataset/flask/bodies/body_248_guide_8_3.py", line 135, in <module>
    raise NoAppException(
__main__.NoAppException: A valid Flask application was not obtained from 'MockModule:test_function()'.
Command exited with non-zero status 1
1.57user 4.90system 0:00.75elapsed 856%CPU (0avgtext+0avgdata 117080maxresident)k
0inputs+112outputs (0major+21805minor)pagefaults 0swaps
