07/28/2024 11:18:05 AM Logging starts
Traceback (most recent call last):
  File "./popular_projects_snippets_dataset/flask/bodies/body_150_refine_0_9.py", line 59, in <module>
    self.session_interface.save_session(self, ctx.session, response)
TypeError: <lambda>() takes 3 positional arguments but 4 were given
Command exited with non-zero status 1
1.62user 4.83system 0:00.74elapsed 863%CPU (0avgtext+0avgdata 117188maxresident)k
0inputs+48outputs (0major+21777minor)pagefaults 0swaps
