07/27/2024 07:27:21 PM Logging starts
Traceback (most recent call last):
  File "./popular_projects_snippets_dataset/flask/bodies/body_0_guide_0_2.py", line 23, in <module>
    raise AttributeError(name) from None
AttributeError: other_name
Command exited with non-zero status 1
1.56user 3.96system 0:00.74elapsed 741%CPU (0avgtext+0avgdata 105124maxresident)k
0inputs+32outputs (0major+23889minor)pagefaults 0swaps
