# Extracted from ./data/repos/pandas/pandas/tests/extension/test_numpy.py
# Failed: DID NOT RAISE <class 'ValueError'>
super().test_setitem_scalar_key_sequence_raise(data)
